# 错误处理机制

+ Error 实例对象
  + JavaScript 解析或运行时，一旦发生错误，引擎就会抛出一个错误对象。JavaScript 原生提供Error构造函数，所有抛出的错误都是这个构造函数的实例
  + JavaScript 语言标准只提到，Error实例对象必须有message属性，表示出错时的提示信息，没有提到其他属性。大多数 JavaScript 引擎，对Error实例还提供name和stack属性，分别表示错误的名称和错误的堆栈，但它们是非标准的，不是每种实现都有
    + message：错误提示信息
    + name：错误名称（非标准属性）
    + stack：错误的堆栈（非标准属性）
+ 原生错误类型
  + Error实例对象是最一般的错误类型，在它的基础上，JavaScript 还定义了其他6种错误对象。也就是说，存在Error的6个派生对象
    + SyntaxError 对象
      + 解析代码时发生的语法错误
    + ReferenceError 对象
      + 引用一个不存在的变量时发生的错误
      + 将一个值分配给无法分配的对象，比如对函数的运行结果或者this赋值
    + RangeError 对象
      + 一个值超出有效范围时发生的错误。主要有几种情况，一是数组长度为负数，二是Number对象的方法参数超出范围，以及函数堆栈超过最大值
    + TypeError 对象
      + 变量或参数不是预期类型时发生的错误
    + URIError 对象
      + URI 相关函数的参数不正确时抛出的错误
    + EvalError 对象
      + eval函数没有被正确执行时，会抛出EvalError错误。该错误类型已经不再使用了，只是为了保证与以前代码兼容，才继续保留
  + 总结
    + 以上这6种派生错误，连同原始的Error对象，都是构造函数。开发者可以使用它们，手动生成错误对象的实例。这些构造函数都接受一个参数，代表错误提示信息（message）
+ 自定义错误
+ throw 语句
  + throw语句的作用是手动中断程序执行，抛出一个错误
  + 实际上，throw可以抛出任何类型的值。也就是说，它的参数可以是任何值
    + 对于 JavaScript 引擎来说，遇到throw语句，程序就中止了。引擎会接收到throw抛出的信息，可能是一个错误实例，也可能是其他类型的值
+ try...catch 结构
  + 一旦发生错误，程序就中止执行了。JavaScript 提供了try...catch结构，允许对错误进行处理，选择是否往下执行
  + catch代码块捕获错误之后，程序不会中断，会按照正常流程继续执行下去
+ finally 代码块
  + try...catch结构允许在最后添加一个finally代码块，表示不管是否出现错误，都必需在最后运行的语句